version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: sunday
      time: "00:00"
    pull-request-branch-name:
      separator: /
    labels:
      - dependencies
    commit-message:
      prefix: depbot
      prefix-development: depbot
      include: scope
    ignore:
      - dependency-name: array-shuffle
      - dependency-name: chalk
      - dependency-name: file-type
      - dependency-name: humanize-string
      - dependency-name: indent-string
      - dependency-name: inquirer
      - dependency-name: term-size
